#pragma once

#define NUM_OF_BITS_IN_A_BYTE               8
#define NUM_OF_HEX_CHARS_IN_A_BYTE          2

//! Start indices in bits
#define ETHERNET_DEST_ADDRESS_START_INDEX   8   * NUM_OF_BITS_IN_A_BYTE
#define ETHERNET_SRC_ADDRESS_START_INDEX    14  * NUM_OF_BITS_IN_A_BYTE
#define ETHERNET_TYPE_START_INDEX           20  * NUM_OF_BITS_IN_A_BYTE

#define ECPRI_PRTOTOCOL_VERSION_START_INDEX 22  * NUM_OF_BITS_IN_A_BYTE
#define ECPRI_RESERVED_AND_C_START_INDEX    22.5* NUM_OF_BITS_IN_A_BYTE
#define ECPRI_MESSAGE_TYPE_START_INDEX      23  * NUM_OF_BITS_IN_A_BYTE
#define ECPRI_PAYLOAD_SIZE_START_INDEX      24  * NUM_OF_BITS_IN_A_BYTE
#define ECPRI_RTC_ID_START_INDEX            26  * NUM_OF_BITS_IN_A_BYTE
#define ECPRI_SEQ_ID_START_INDEX            28  * NUM_OF_BITS_IN_A_BYTE

//! Field lengths in bits
#define ETHERNET_DEST_ADDRESS_LENGTH        6   * NUM_OF_BITS_IN_A_BYTE
#define ETHERNET_SRC_ADDRESS_LENGTH         6   * NUM_OF_BITS_IN_A_BYTE
#define ETHERNET_TYPE_LENGTH                2   * NUM_OF_BITS_IN_A_BYTE
#define ETHERNET_FCS_LENGTH                 4   * NUM_OF_BITS_IN_A_BYTE

#define ECPRI_PRTOTOCOL_VERSION_LENGTH      0.5 * NUM_OF_BITS_IN_A_BYTE
#define ECPRI_RESERVED_AND_C_LENGTH         0.5 * NUM_OF_BITS_IN_A_BYTE
#define ECPRI_MESSAGE_TYPE_LENGTH           1  * NUM_OF_BITS_IN_A_BYTE
#define ECPRI_PAYLOAD_SIZE_LENGTH           2  * NUM_OF_BITS_IN_A_BYTE
#define ECPRI_RTC_ID_LENGTH                 2  * NUM_OF_BITS_IN_A_BYTE
#define ECPRI_SEQ_ID_LENGTH                 2  * NUM_OF_BITS_IN_A_BYTE

#define TYPE_ECPRI  "AEFE"

enum class FrameType
{
    RAW_ETHERNET,
    ECPRI_CONTROL
};

enum class EthernetFrameFields
{
    DEST_ADDRESS,
    SOURCE_ADDRESS,
    TYPE,
    FCS
};

enum class ECPRIFrameFields
{
    PRTOTOCOL_VERSION,
    RESERVED_AND_C,
    MESSAGE_TYPE,
    PAYLOAD_SIZE,
    RTC_ID,
    SEQ_ID
};
