/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.hdl.ui.quickfix;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.model.edit.ISemanticModification;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import org.xtext.example.hdl.hDL.PTArchDecl;
import org.xtext.example.hdl.hDL.PTSignalAssign;
import org.xtext.example.hdl.hDL.PTSignalDecl;

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class HDLQuickfixProvider extends DefaultQuickfixProvider {

	@Fix("ISSUE_CODE_TYPE_MISMATCH")
	public void fixRHS(final Issue issue, IssueResolutionAcceptor acceptor) {
		//get issue data
		final String newSignalName = issue.getData()[0];
		if(newSignalName.isEmpty()) return;
		
		// do the modification
		final ISemanticModification modification = new ISemanticModification() {
			@Override
			public void apply(final EObject issueObject, final IModificationContext context)
			throws Exception {
				// fix the end name
		        if(issueObject instanceof PTSignalAssign) {
		        	//Get signal declaration with name = newSignalName
		        	
		        	// Get the surrounding architecture
		    		PTArchDecl ad = (PTArchDecl) issueObject.eContainer();
		    		if(ad == null) return;
		    		for(PTSignalDecl currDecl : ad.getSignalDecls()) {
		    			if(currDecl == null) continue;
		    			if(currDecl.getName().equalsIgnoreCase(newSignalName)) {
		    				// Apply the fix
		    				((PTSignalAssign)issueObject).getRhs().setId(currDecl);
		    				break;
		    			}
		    		}
		    		
		        	
		        }
			}
		};
	
		acceptor.accept(issue, 
	              "Change to '" + newSignalName + "'",
	              newSignalName, // description
	              "", // image
	              modification);
	}
}


